-- Seed import batch 7: mined from the 'หาคู่ย้ายสับเปลี่ยน เอกศิลปศึกษา, ทัศนศิลป์,
-- ดนตรี, นาฏศิลป์' megathread. Unlike every prior batch, this one was pasted
-- WITHOUT Facebook profile links, so there's no numeric FB id to key off of.
-- Per explicit instruction, each teacher gets a random 'seed:manual:<hex>' id
-- (generated by Postgres at insert time via gen_random_bytes) instead of
-- 'seed:fb:<id>', and facebook_url is left null. This means these records
-- can never be claimed via the normal /join/<code> flow tied to a Facebook
-- account matching, and can't be deduped against future re-scrapes of the
-- same thread by id the way seed:fb: records can.
-- To remove this batch: delete from teachers where line_user_id like 'seed:manual:%'
-- and created_at >= now() - interval '1 hour'; -- adjust the interval to taste


-- 1) PurpleCamel6050 (ศิลปะ) — secondary, กาญจนบุรี
with t as (
  insert into teachers (line_user_id, display_name, position, service_type, origin_province, teaching_group, subject, transfer_round, transfer_year, facebook_url, source, invite_code)
  values ('seed:manual:' || encode(gen_random_bytes(6), 'hex'), 'PurpleCamel6050', 'teacher', 'secondary', 'กาญจนบุรี', 'art', 'ศิลปะ', null, null, null, 'facebook_import', encode(gen_random_bytes(4), 'hex'))
  returning id
)
insert into destinations (teacher_id, province)
select id, 'พัทลุง' from t
union all
select id, 'สงขลา' from t;

-- 2) Saipanya Makboon (ศิลปะ) — primary, กำแพงเพชร
with t as (
  insert into teachers (line_user_id, display_name, position, service_type, origin_province, origin_zone, teaching_group, subject, transfer_round, transfer_year, facebook_url, source, invite_code)
  values ('seed:manual:' || encode(gen_random_bytes(6), 'hex'), 'Saipanya Makboon', 'teacher', 'primary', 'กำแพงเพชร', 'เขต 2', 'art', 'ศิลปะ', null, null, null, 'facebook_import', encode(gen_random_bytes(4), 'hex'))
  returning id
)
insert into destinations (teacher_id, province, zone)
select id, 'นครสวรรค์', 'เขต 3' from t;

-- 3) สาย ลม (ศิลปศึกษา) — secondary, ตราด
with t as (
  insert into teachers (line_user_id, display_name, position, service_type, origin_province, origin_district, teaching_group, subject, transfer_round, transfer_year, facebook_url, source, invite_code)
  values ('seed:manual:' || encode(gen_random_bytes(6), 'hex'), 'สาย ลม', 'teacher', 'secondary', 'ตราด', 'คลองใหญ่', 'art', 'ศิลปศึกษา', null, null, null, 'facebook_import', encode(gen_random_bytes(4), 'hex'))
  returning id
)
insert into destinations (teacher_id, province)
select id, 'ขอนแก่น' from t;

-- 4) Purimprat Muensriprom (ศิลปศึกษา) — secondary, นครราชสีมา
with t as (
  insert into teachers (line_user_id, display_name, position, service_type, origin_province, teaching_group, subject, transfer_round, transfer_year, facebook_url, source, invite_code)
  values ('seed:manual:' || encode(gen_random_bytes(6), 'hex'), 'Purimprat Muensriprom', 'teacher', 'secondary', 'นครราชสีมา', 'art', 'ศิลปศึกษา', null, null, null, 'facebook_import', encode(gen_random_bytes(4), 'hex'))
  returning id
)
insert into destinations (teacher_id, province)
select id, 'จันทบุรี' from t;

-- 5) Pakamas Makmo (ทัศนศิลป์) — secondary, พิษณุโลก
with t as (
  insert into teachers (line_user_id, display_name, position, service_type, origin_province, teaching_group, subject, transfer_round, transfer_year, facebook_url, source, invite_code)
  values ('seed:manual:' || encode(gen_random_bytes(6), 'hex'), 'Pakamas Makmo', 'teacher', 'secondary', 'พิษณุโลก', 'art', 'ทัศนศิลป์', null, null, null, 'facebook_import', encode(gen_random_bytes(4), 'hex'))
  returning id
)
insert into destinations (teacher_id, province)
select id, 'อุตรดิตถ์' from t;

-- 6) Imajoy Salasaton (ศิลปะ) — primary, สงขลา
with t as (
  insert into teachers (line_user_id, display_name, position, service_type, origin_province, origin_district, origin_zone, teaching_group, subject, transfer_round, transfer_year, facebook_url, source, invite_code)
  values ('seed:manual:' || encode(gen_random_bytes(6), 'hex'), 'Imajoy Salasaton', 'teacher', 'primary', 'สงขลา', 'สะเดา', 'เขต 3', 'art', 'ศิลปะ', null, null, null, 'facebook_import', encode(gen_random_bytes(4), 'hex'))
  returning id
)
insert into destinations (teacher_id, province, zone, district)
select id, 'สงขลา', 'เขต 3', 'นาทวี' from t;

-- 7) ธีรสุต วงค์อุประ (นาฏศิลป์) — secondary, ภูเก็ต
with t as (
  insert into teachers (line_user_id, display_name, position, service_type, origin_province, origin_district, teaching_group, subject, transfer_round, transfer_year, facebook_url, source, invite_code)
  values ('seed:manual:' || encode(gen_random_bytes(6), 'hex'), 'ธีรสุต วงค์อุประ', 'teacher', 'secondary', 'ภูเก็ต', 'ถลาง', 'art', 'นาฏศิลป์', null, null, null, 'facebook_import', encode(gen_random_bytes(4), 'hex'))
  returning id
)
insert into destinations (teacher_id, province, district)
select id, 'นครศรีธรรมราช', 'เมือง' from t;

-- 8) Noppakao Manussakarn (ทัศนศิลป์) — secondary, สมุทรปราการ
with t as (
  insert into teachers (line_user_id, display_name, position, service_type, origin_province, teaching_group, subject, transfer_round, transfer_year, facebook_url, source, invite_code)
  values ('seed:manual:' || encode(gen_random_bytes(6), 'hex'), 'Noppakao Manussakarn', 'teacher', 'secondary', 'สมุทรปราการ', 'art', 'ทัศนศิลป์', null, null, null, 'facebook_import', encode(gen_random_bytes(4), 'hex'))
  returning id
)
insert into destinations (teacher_id, province)
select id, 'นครปฐม' from t
union all
select id, 'ราชบุรี' from t;

-- 9) CapableSeahorse7689 — secondary, อุบลราชธานี
with t as (
  insert into teachers (line_user_id, display_name, position, service_type, origin_province, teaching_group, subject, transfer_round, transfer_year, facebook_url, source, invite_code)
  values ('seed:manual:' || encode(gen_random_bytes(6), 'hex'), 'CapableSeahorse7689', 'teacher', 'secondary', 'อุบลราชธานี', 'art', null, '1', 2027, null, 'facebook_import', encode(gen_random_bytes(4), 'hex'))
  returning id
)
insert into destinations (teacher_id, province)
select id, 'กาฬสินธุ์' from t;

-- 10) Kajonyos Klin-Ubon (ดนตรีไทย) — primary, กาญจนบุรี
with t as (
  insert into teachers (line_user_id, display_name, position, service_type, origin_province, origin_zone, teaching_group, subject, transfer_round, transfer_year, facebook_url, source, invite_code)
  values ('seed:manual:' || encode(gen_random_bytes(6), 'hex'), 'Kajonyos Klin-Ubon', 'teacher', 'primary', 'กาญจนบุรี', 'เขต 2', 'art', 'ดนตรีไทย', null, null, null, 'facebook_import', encode(gen_random_bytes(4), 'hex'))
  returning id
)
insert into destinations (teacher_id, province, zone)
select id, 'กาญจนบุรี', 'เขต 1, เขต 4' from t;

-- 11) Sor Art Art (ทัศนศิลป์) — secondary, บึงกาฬ
with t as (
  insert into teachers (line_user_id, display_name, position, service_type, origin_province, origin_district, teaching_group, subject, transfer_round, transfer_year, facebook_url, source, invite_code)
  values ('seed:manual:' || encode(gen_random_bytes(6), 'hex'), 'Sor Art Art', 'teacher', 'secondary', 'บึงกาฬ', 'เซกา', 'art', 'ทัศนศิลป์', null, null, null, 'facebook_import', encode(gen_random_bytes(4), 'hex'))
  returning id
)
insert into destinations (teacher_id, province)
select id, 'นครราชสีมา' from t;

-- 12) WA RA (ศิลปะ) — primary, ระยอง
with t as (
  insert into teachers (line_user_id, display_name, position, service_type, origin_province, origin_zone, teaching_group, subject, transfer_round, transfer_year, facebook_url, source, invite_code)
  values ('seed:manual:' || encode(gen_random_bytes(6), 'hex'), 'WA RA', 'teacher', 'primary', 'ระยอง', 'เขต 1', 'art', 'ศิลปะ', null, null, null, 'facebook_import', encode(gen_random_bytes(4), 'hex'))
  returning id
)
insert into destinations (teacher_id, province, zone)
select id, 'นครพนม', 'เขต 1' from t;

-- 13) Kru Fueng Story (นาฏศิลป์) — primary, อุบลราชธานี
with t as (
  insert into teachers (line_user_id, display_name, position, service_type, origin_province, origin_district, origin_zone, teaching_group, subject, transfer_round, transfer_year, facebook_url, source, invite_code)
  values ('seed:manual:' || encode(gen_random_bytes(6), 'hex'), 'Kru Fueng Story', 'teacher', 'primary', 'อุบลราชธานี', 'โขงเจียม', 'เขต 3', 'art', 'นาฏศิลป์', null, null, null, 'facebook_import', encode(gen_random_bytes(4), 'hex'))
  returning id
)
insert into destinations (teacher_id, province, zone, district)
select id, 'อุบลราชธานี', 'เขต 2', 'ตระการพืชผล' from t;

-- 14) Sivimon Thepraksa (ทัศนศิลป์) — secondary, แม่ฮ่องสอน
with t as (
  insert into teachers (line_user_id, display_name, position, service_type, origin_province, teaching_group, subject, transfer_round, transfer_year, facebook_url, source, invite_code)
  values ('seed:manual:' || encode(gen_random_bytes(6), 'hex'), 'Sivimon Thepraksa', 'teacher', 'secondary', 'แม่ฮ่องสอน', 'art', 'ทัศนศิลป์', null, null, null, 'facebook_import', encode(gen_random_bytes(4), 'hex'))
  returning id
)
insert into destinations (teacher_id, province)
select id, 'เชียงใหม่' from t
union all
select id, 'พะเยา' from t
union all
select id, 'เชียงราย' from t;

-- 15) BlueBison3616 (นาฏศิลป์) — primary, สุรินทร์
with t as (
  insert into teachers (line_user_id, display_name, position, service_type, origin_province, origin_zone, teaching_group, subject, transfer_round, transfer_year, facebook_url, source, invite_code)
  values ('seed:manual:' || encode(gen_random_bytes(6), 'hex'), 'BlueBison3616', 'teacher', 'primary', 'สุรินทร์', 'เขต 1', 'art', 'นาฏศิลป์', null, null, null, 'facebook_import', encode(gen_random_bytes(4), 'hex'))
  returning id
)
insert into destinations (teacher_id, province, district)
select id, 'ชลบุรี', 'ศรีราชา' from t;

-- 16) Nattapong Suksong (ศิลปศึกษา) — primary, ภูเก็ต
with t as (
  insert into teachers (line_user_id, display_name, position, service_type, origin_province, origin_district, teaching_group, subject, transfer_round, transfer_year, facebook_url, source, invite_code)
  values ('seed:manual:' || encode(gen_random_bytes(6), 'hex'), 'Nattapong Suksong', 'teacher', 'primary', 'ภูเก็ต', 'เมือง', 'art', 'ศิลปศึกษา', null, null, null, 'facebook_import', encode(gen_random_bytes(4), 'hex'))
  returning id
)
insert into destinations (teacher_id, province)
select id, 'สงขลา' from t
union all
select id, 'พัทลุง' from t;

-- 17) Tongtoy Sudarat (นาฏศิลป์) — primary, ร้อยเอ็ด
with t as (
  insert into teachers (line_user_id, display_name, position, service_type, origin_province, origin_zone, teaching_group, subject, transfer_round, transfer_year, facebook_url, source, invite_code)
  values ('seed:manual:' || encode(gen_random_bytes(6), 'hex'), 'Tongtoy Sudarat', 'teacher', 'primary', 'ร้อยเอ็ด', 'เขต 2', 'art', 'นาฏศิลป์', null, null, null, 'facebook_import', encode(gen_random_bytes(4), 'hex'))
  returning id
)
insert into destinations (teacher_id, province, zone)
select id, 'ร้อยเอ็ด', 'เขต 1' from t;

-- 18) Sirikorn Jeraja (นาฏศิลป์) — primary, ชัยภูมิ
with t as (
  insert into teachers (line_user_id, display_name, position, service_type, origin_province, origin_zone, teaching_group, subject, transfer_round, transfer_year, facebook_url, source, invite_code)
  values ('seed:manual:' || encode(gen_random_bytes(6), 'hex'), 'Sirikorn Jeraja', 'teacher', 'primary', 'ชัยภูมิ', 'เขต 3', 'art', 'นาฏศิลป์', null, null, null, 'facebook_import', encode(gen_random_bytes(4), 'hex'))
  returning id
)
insert into destinations (teacher_id, province, zone)
select id, 'ชัยภูมิ', 'เขต 1' from t;

-- 19) Kittiya Jarujinda (นาฏศิลป์) — primary, เชียงใหม่
with t as (
  insert into teachers (line_user_id, display_name, position, service_type, origin_province, origin_district, origin_zone, teaching_group, subject, transfer_round, transfer_year, facebook_url, source, invite_code)
  values ('seed:manual:' || encode(gen_random_bytes(6), 'hex'), 'Kittiya Jarujinda', 'teacher', 'primary', 'เชียงใหม่', 'แม่ริม', 'เขต 2', 'art', 'นาฏศิลป์', null, null, null, 'facebook_import', encode(gen_random_bytes(4), 'hex'))
  returning id
)
insert into destinations (teacher_id, province, zone)
select id, 'พะเยา', 'เขต 2' from t;

-- 20) Peam Patthanun (ทัศนศิลป์) — primary, ลพบุรี
with t as (
  insert into teachers (line_user_id, display_name, position, service_type, origin_province, origin_zone, teaching_group, subject, transfer_round, transfer_year, facebook_url, source, invite_code)
  values ('seed:manual:' || encode(gen_random_bytes(6), 'hex'), 'Peam Patthanun', 'teacher', 'primary', 'ลพบุรี', 'เขต 2', 'art', 'ทัศนศิลป์', null, null, null, 'facebook_import', encode(gen_random_bytes(4), 'hex'))
  returning id
)
insert into destinations (teacher_id, province)
select id, 'สิงห์บุรี' from t;

-- 21) Beam Varinee (นาฏศิลป์) — primary, ขอนแก่น
with t as (
  insert into teachers (line_user_id, display_name, position, service_type, origin_province, origin_district, origin_zone, teaching_group, subject, transfer_round, transfer_year, facebook_url, source, invite_code)
  values ('seed:manual:' || encode(gen_random_bytes(6), 'hex'), 'Beam Varinee', 'teacher', 'primary', 'ขอนแก่น', 'แวงน้อย', 'เขต 3', 'art', 'นาฏศิลป์', null, null, null, 'facebook_import', encode(gen_random_bytes(4), 'hex'))
  returning id
)
insert into destinations (teacher_id, province, zone)
select id, 'ขอนแก่น', 'เขต 5' from t;

-- 22) เต้ย ไตเติ้ล (นาฏศิลป์) — primary, สกลนคร
with t as (
  insert into teachers (line_user_id, display_name, position, service_type, origin_province, origin_zone, teaching_group, subject, transfer_round, transfer_year, facebook_url, source, invite_code)
  values ('seed:manual:' || encode(gen_random_bytes(6), 'hex'), 'เต้ย ไตเติ้ล', 'teacher', 'primary', 'สกลนคร', 'เขต 2', 'art', 'นาฏศิลป์', null, null, null, 'facebook_import', encode(gen_random_bytes(4), 'hex'))
  returning id
)
insert into destinations (teacher_id, province, zone)
select id, 'นครพนม', 'เขต 2' from t;

-- 23) ThoughtfulSalamander2347 (ศิลปะ) — primary, นครศรีธรรมราช
with t as (
  insert into teachers (line_user_id, display_name, position, service_type, origin_province, origin_zone, teaching_group, subject, transfer_round, transfer_year, facebook_url, source, invite_code)
  values ('seed:manual:' || encode(gen_random_bytes(6), 'hex'), 'ThoughtfulSalamander2347', 'teacher', 'primary', 'นครศรีธรรมราช', 'เขต 2', 'art', 'ศิลปะ', null, null, null, 'facebook_import', encode(gen_random_bytes(4), 'hex'))
  returning id
)
insert into destinations (teacher_id, province)
select id, 'ตรัง' from t
union all
select id, 'พัทลุง' from t;

-- 24) Pruethinan Kamalas Na Ayudhaya (ทัศนศิลป์) — secondary, สมุทรปราการ
with t as (
  insert into teachers (line_user_id, display_name, position, service_type, origin_province, teaching_group, subject, transfer_round, transfer_year, facebook_url, source, invite_code)
  values ('seed:manual:' || encode(gen_random_bytes(6), 'hex'), 'Pruethinan Kamalas Na Ayudhaya', 'teacher', 'secondary', 'สมุทรปราการ', 'art', 'ทัศนศิลป์', null, null, null, 'facebook_import', encode(gen_random_bytes(4), 'hex'))
  returning id
)
insert into destinations (teacher_id, province)
select id, 'นนทบุรี' from t;

-- 25) Laila Sadee (ศิลปศึกษา) — primary, ปัตตานี
with t as (
  insert into teachers (line_user_id, display_name, position, service_type, origin_province, origin_district, origin_zone, teaching_group, subject, transfer_round, transfer_year, facebook_url, source, invite_code)
  values ('seed:manual:' || encode(gen_random_bytes(6), 'hex'), 'Laila Sadee', 'teacher', 'primary', 'ปัตตานี', 'ปะนาเระ', 'เขต 1', 'art', 'ศิลปศึกษา', null, null, null, 'facebook_import', encode(gen_random_bytes(4), 'hex'))
  returning id
)
insert into destinations (teacher_id, province, zone)
select id, 'ปัตตานี', 'เขต 1 (เมือง), เขต 2 (ยะรัง)' from t;

-- 26) Krukla Chin (ศิลปศึกษา) — primary, นครราชสีมา
with t as (
  insert into teachers (line_user_id, display_name, position, service_type, origin_province, origin_zone, teaching_group, subject, transfer_round, transfer_year, facebook_url, source, invite_code)
  values ('seed:manual:' || encode(gen_random_bytes(6), 'hex'), 'Krukla Chin', 'teacher', 'primary', 'นครราชสีมา', 'เขต 4', 'art', 'ศิลปศึกษา', null, null, null, 'facebook_import', encode(gen_random_bytes(4), 'hex'))
  returning id
)
insert into destinations (teacher_id, province, zone)
select id, 'นครราชสีมา', 'เขต 1' from t;

-- 27) AdventurousParsnip4148 (ดนตรีศึกษา) — secondary, สุรินทร์
with t as (
  insert into teachers (line_user_id, display_name, position, service_type, origin_province, teaching_group, subject, transfer_round, transfer_year, facebook_url, source, invite_code)
  values ('seed:manual:' || encode(gen_random_bytes(6), 'hex'), 'AdventurousParsnip4148', 'teacher', 'secondary', 'สุรินทร์', 'art', 'ดนตรีศึกษา', null, null, null, 'facebook_import', encode(gen_random_bytes(4), 'hex'))
  returning id
)
insert into destinations (teacher_id, province)
select id, 'ขอนแก่น' from t;

-- 28) เอิร์น เอยยยยย (ศิลปะ) — primary, สมุทรสาคร
with t as (
  insert into teachers (line_user_id, display_name, position, service_type, origin_province, teaching_group, subject, transfer_round, transfer_year, facebook_url, source, invite_code)
  values ('seed:manual:' || encode(gen_random_bytes(6), 'hex'), 'เอิร์น เอยยยยย', 'teacher', 'primary', 'สมุทรสาคร', 'art', 'ศิลปะ', null, null, null, 'facebook_import', encode(gen_random_bytes(4), 'hex'))
  returning id
)
insert into destinations (teacher_id, province, zone)
select id, 'นครราชสีมา', 'เขต 6, เขต 7' from t
union all
select id, 'กรุงเทพมหานคร', 'เขต 1' from t;

-- 29) kruphatcha9533 (นาฏศิลป์) — secondary, มหาสารคาม
with t as (
  insert into teachers (line_user_id, display_name, position, service_type, origin_province, teaching_group, subject, transfer_round, transfer_year, facebook_url, source, invite_code)
  values ('seed:manual:' || encode(gen_random_bytes(6), 'hex'), 'kruphatcha9533', 'teacher', 'secondary', 'มหาสารคาม', 'art', 'นาฏศิลป์', null, null, null, 'facebook_import', encode(gen_random_bytes(4), 'hex'))
  returning id
)
insert into destinations (teacher_id, province)
select id, 'ขอนแก่น' from t;

-- 30) Boonwilai Thongdeeying (ศิลปศึกษา) — secondary, นราธิวาส
with t as (
  insert into teachers (line_user_id, display_name, position, service_type, origin_province, teaching_group, subject, transfer_round, transfer_year, facebook_url, source, invite_code)
  values ('seed:manual:' || encode(gen_random_bytes(6), 'hex'), 'Boonwilai Thongdeeying', 'teacher', 'secondary', 'นราธิวาส', 'art', 'ศิลปศึกษา', null, null, null, 'facebook_import', encode(gen_random_bytes(4), 'hex'))
  returning id
)
insert into destinations (teacher_id, province)
select id, 'ตรัง' from t;

-- 31) Kru Ben Janpen (ดนตรีไทย) — primary, ชลบุรี
with t as (
  insert into teachers (line_user_id, display_name, position, service_type, origin_province, origin_zone, teaching_group, subject, transfer_round, transfer_year, facebook_url, source, invite_code)
  values ('seed:manual:' || encode(gen_random_bytes(6), 'hex'), 'Kru Ben Janpen', 'teacher', 'primary', 'ชลบุรี', 'เขต 3', 'art', 'ดนตรีไทย', null, null, null, 'facebook_import', encode(gen_random_bytes(4), 'hex'))
  returning id
)
insert into destinations (teacher_id, province, zone)
select id, 'ราชบุรี', 'เขต 2' from t;

-- 32) TA Sketch (ศิลปศึกษา) — primary, ชัยภูมิ
with t as (
  insert into teachers (line_user_id, display_name, position, service_type, origin_province, origin_zone, teaching_group, subject, transfer_round, transfer_year, facebook_url, source, invite_code)
  values ('seed:manual:' || encode(gen_random_bytes(6), 'hex'), 'TA Sketch', 'teacher', 'primary', 'ชัยภูมิ', 'เขต 3', 'art', 'ศิลปศึกษา', null, null, null, 'facebook_import', encode(gen_random_bytes(4), 'hex'))
  returning id
)
insert into destinations (teacher_id, province, zone)
select id, 'ชัยภูมิ', 'เขต 2' from t
union all
select id, 'ขอนแก่น', 'เขต 5, เขต 1' from t;

-- 33) PI YA (ทัศนศิลป์) — secondary, นนทบุรี
with t as (
  insert into teachers (line_user_id, display_name, position, service_type, origin_province, teaching_group, subject, transfer_round, transfer_year, facebook_url, source, invite_code)
  values ('seed:manual:' || encode(gen_random_bytes(6), 'hex'), 'PI YA', 'teacher', 'secondary', 'นนทบุรี', 'art', 'ทัศนศิลป์', null, null, null, 'facebook_import', encode(gen_random_bytes(4), 'hex'))
  returning id
)
insert into destinations (teacher_id, province)
select id, 'นครศรีธรรมราช' from t;

-- 34) Tanisorn Udomsin (ทัศนศิลป์) — primary, นครศรีธรรมราช
with t as (
  insert into teachers (line_user_id, display_name, position, service_type, origin_province, origin_zone, teaching_group, subject, transfer_round, transfer_year, facebook_url, source, invite_code)
  values ('seed:manual:' || encode(gen_random_bytes(6), 'hex'), 'Tanisorn Udomsin', 'teacher', 'primary', 'นครศรีธรรมราช', 'เขต 4', 'art', 'ทัศนศิลป์', null, null, null, 'facebook_import', encode(gen_random_bytes(4), 'hex'))
  returning id
)
insert into destinations (teacher_id, province, zone)
select id, 'นครศรีธรรมราช', 'เขต 1-2' from t;

-- 35) Flu Fluke (ดนตรีสากล) — primary, ชลบุรี
with t as (
  insert into teachers (line_user_id, display_name, position, service_type, origin_province, origin_zone, teaching_group, subject, transfer_round, transfer_year, facebook_url, source, invite_code)
  values ('seed:manual:' || encode(gen_random_bytes(6), 'hex'), 'Flu Fluke', 'teacher', 'primary', 'ชลบุรี', 'เขต 1', 'art', 'ดนตรีสากล', null, null, null, 'facebook_import', encode(gen_random_bytes(4), 'hex'))
  returning id
)
insert into destinations (teacher_id, province, zone)
select id, 'ระยอง', 'เขต 1' from t;

-- 36) อา รุ (ศิลปะ) — primary, จันทบุรี
with t as (
  insert into teachers (line_user_id, display_name, position, service_type, origin_province, origin_zone, teaching_group, subject, transfer_round, transfer_year, facebook_url, source, invite_code)
  values ('seed:manual:' || encode(gen_random_bytes(6), 'hex'), 'อา รุ', 'teacher', 'primary', 'จันทบุรี', 'เขต 2', 'art', 'ศิลปะ', null, null, null, 'facebook_import', encode(gen_random_bytes(4), 'hex'))
  returning id
)
insert into destinations (teacher_id, province, zone)
select id, 'มหาสารคาม', 'เขต 2' from t;

-- 37) Earn Waranyada (ดนตรี) — primary, ประจวบคีรีขันธ์
with t as (
  insert into teachers (line_user_id, display_name, position, service_type, origin_province, origin_zone, teaching_group, subject, transfer_round, transfer_year, facebook_url, source, invite_code)
  values ('seed:manual:' || encode(gen_random_bytes(6), 'hex'), 'Earn Waranyada', 'teacher', 'primary', 'ประจวบคีรีขันธ์', 'เขต 1', 'art', 'ดนตรี', null, null, null, 'facebook_import', encode(gen_random_bytes(4), 'hex'))
  returning id
)
insert into destinations (teacher_id, province, zone)
select id, 'เพชรบุรี', 'เขต 1' from t;

-- 38) Khunpooh24 (นาฏศิลป์) — primary, ฉะเชิงเทรา
with t as (
  insert into teachers (line_user_id, display_name, position, service_type, origin_province, origin_zone, teaching_group, subject, transfer_round, transfer_year, facebook_url, source, invite_code)
  values ('seed:manual:' || encode(gen_random_bytes(6), 'hex'), 'Khunpooh24', 'teacher', 'primary', 'ฉะเชิงเทรา', 'เขต 2', 'art', 'นาฏศิลป์', null, null, null, 'facebook_import', encode(gen_random_bytes(4), 'hex'))
  returning id
)
insert into destinations (teacher_id, province)
select id, 'สุรินทร์' from t
union all
select id, 'บุรีรัมย์' from t;

-- 39) Jeerada Tienkow (นาฏศิลป์) — primary, ประจวบคีรีขันธ์
with t as (
  insert into teachers (line_user_id, display_name, position, service_type, origin_province, origin_zone, teaching_group, subject, transfer_round, transfer_year, facebook_url, source, invite_code)
  values ('seed:manual:' || encode(gen_random_bytes(6), 'hex'), 'Jeerada Tienkow', 'teacher', 'primary', 'ประจวบคีรีขันธ์', 'เขต 1', 'art', 'นาฏศิลป์', null, null, null, 'facebook_import', encode(gen_random_bytes(4), 'hex'))
  returning id
)
insert into destinations (teacher_id, province, zone)
select id, 'ระยอง', 'เขต 1' from t;

-- 40) SincereHamster8508 (ศิลปะ) — primary, นราธิวาส
with t as (
  insert into teachers (line_user_id, display_name, position, service_type, origin_province, origin_zone, teaching_group, subject, transfer_round, transfer_year, facebook_url, source, invite_code)
  values ('seed:manual:' || encode(gen_random_bytes(6), 'hex'), 'SincereHamster8508', 'teacher', 'primary', 'นราธิวาส', 'เขต 2', 'art', 'ศิลปะ', null, null, null, 'facebook_import', encode(gen_random_bytes(4), 'hex'))
  returning id
)
insert into destinations (teacher_id, province)
select id, 'สตูล' from t;

-- 41) Tawan Jesk (ทัศนศิลป์) — secondary, นนทบุรี
with t as (
  insert into teachers (line_user_id, display_name, position, service_type, origin_province, origin_zone, teaching_group, subject, transfer_round, transfer_year, facebook_url, source, invite_code)
  values ('seed:manual:' || encode(gen_random_bytes(6), 'hex'), 'Tawan Jesk', 'teacher', 'secondary', 'นนทบุรี', 'เขต 2', 'art', 'ทัศนศิลป์', null, null, null, 'facebook_import', encode(gen_random_bytes(4), 'hex'))
  returning id
)
insert into destinations (teacher_id, province, zone)
select id, 'กรุงเทพมหานคร', 'เขต 2' from t;

-- 42) Budsayarak Far Pakdeebodin (นาฏศิลป์) — primary, บึงกาฬ
with t as (
  insert into teachers (line_user_id, display_name, position, service_type, origin_province, origin_district, teaching_group, subject, transfer_round, transfer_year, facebook_url, source, invite_code)
  values ('seed:manual:' || encode(gen_random_bytes(6), 'hex'), 'Budsayarak Far Pakdeebodin', 'teacher', 'primary', 'บึงกาฬ', 'พรเจริญ', 'art', 'นาฏศิลป์', null, null, null, 'facebook_import', encode(gen_random_bytes(4), 'hex'))
  returning id
)
insert into destinations (teacher_id, province)
select id, 'ขอนแก่น' from t
union all
select id, 'มหาสารคาม' from t;

-- 43) CaptivatingPineapple6346 (นาฏศิลป์) — secondary, สมุทรปราการ
with t as (
  insert into teachers (line_user_id, display_name, position, service_type, origin_province, teaching_group, subject, transfer_round, transfer_year, facebook_url, source, invite_code)
  values ('seed:manual:' || encode(gen_random_bytes(6), 'hex'), 'CaptivatingPineapple6346', 'teacher', 'secondary', 'สมุทรปราการ', 'art', 'นาฏศิลป์', null, null, null, 'facebook_import', encode(gen_random_bytes(4), 'hex'))
  returning id
)
insert into destinations (teacher_id, province, zone)
select id, 'กรุงเทพมหานคร', 'เขต 1, เขต 2' from t;

-- 44) Leedong Art Voice (ศิลปะ) — primary, นครศรีธรรมราช
with t as (
  insert into teachers (line_user_id, display_name, position, service_type, origin_province, origin_zone, teaching_group, subject, transfer_round, transfer_year, facebook_url, source, invite_code)
  values ('seed:manual:' || encode(gen_random_bytes(6), 'hex'), 'Leedong Art Voice', 'teacher', 'primary', 'นครศรีธรรมราช', 'เขต 2', 'art', 'ศิลปะ', null, null, null, 'facebook_import', encode(gen_random_bytes(4), 'hex'))
  returning id
)
insert into destinations (teacher_id, province)
select id, 'สุราษฎร์ธานี' from t;

-- 45) Sutharnx June (นาฏศิลป์) — secondary, กาญจนบุรี
with t as (
  insert into teachers (line_user_id, display_name, position, service_type, origin_province, teaching_group, subject, transfer_round, transfer_year, facebook_url, source, invite_code)
  values ('seed:manual:' || encode(gen_random_bytes(6), 'hex'), 'Sutharnx June', 'teacher', 'secondary', 'กาญจนบุรี', 'art', 'นาฏศิลป์', null, null, null, 'facebook_import', encode(gen_random_bytes(4), 'hex'))
  returning id
)
insert into destinations (teacher_id, province)
select id, 'เพชรบุรี' from t
union all
select id, 'ประจวบคีรีขันธ์' from t;

-- 46) Warocha Sae-ngow (ศิลปะ) — primary, กรุงเทพมหานคร
with t as (
  insert into teachers (line_user_id, display_name, position, service_type, origin_province, teaching_group, subject, transfer_round, transfer_year, facebook_url, source, invite_code)
  values ('seed:manual:' || encode(gen_random_bytes(6), 'hex'), 'Warocha Sae-ngow', 'teacher', 'primary', 'กรุงเทพมหานคร', 'art', 'ศิลปะ', null, null, null, 'facebook_import', encode(gen_random_bytes(4), 'hex'))
  returning id
)
insert into destinations (teacher_id, province, zone)
select id, 'ลำปาง', 'เขต 1' from t;

-- 47) Supanut Makpramool (ดนตรีไทย) — primary, พระนครศรีอยุธยา
with t as (
  insert into teachers (line_user_id, display_name, position, service_type, origin_province, origin_zone, teaching_group, subject, transfer_round, transfer_year, facebook_url, source, invite_code)
  values ('seed:manual:' || encode(gen_random_bytes(6), 'hex'), 'Supanut Makpramool', 'teacher', 'primary', 'พระนครศรีอยุธยา', 'เขต 1', 'art', 'ดนตรีไทย', null, null, null, 'facebook_import', encode(gen_random_bytes(4), 'hex'))
  returning id
)
insert into destinations (teacher_id, province, zone)
select id, 'พระนครศรีอยุธยา', 'เขต 2' from t;

-- 48) ผู้ทรงศิลป์ (ศิลปศึกษา) — secondary, ศรีสะเกษ
with t as (
  insert into teachers (line_user_id, display_name, position, service_type, origin_province, teaching_group, subject, transfer_round, transfer_year, facebook_url, source, invite_code)
  values ('seed:manual:' || encode(gen_random_bytes(6), 'hex'), 'ผู้ทรงศิลป์', 'teacher', 'secondary', 'ศรีสะเกษ', 'art', 'ศิลปศึกษา', null, null, null, 'facebook_import', encode(gen_random_bytes(4), 'hex'))
  returning id
)
insert into destinations (teacher_id, province, district)
select id, 'ศรีสะเกษ', 'เมือง' from t;

-- 49) TT2659 (ดนตรีไทย) — secondary, กรุงเทพมหานคร
with t as (
  insert into teachers (line_user_id, display_name, position, service_type, origin_province, origin_zone, teaching_group, subject, transfer_round, transfer_year, facebook_url, source, invite_code)
  values ('seed:manual:' || encode(gen_random_bytes(6), 'hex'), 'TT2659', 'teacher', 'secondary', 'กรุงเทพมหานคร', 'เขต 2', 'art', 'ดนตรีไทย', null, null, null, 'facebook_import', encode(gen_random_bytes(4), 'hex'))
  returning id
)
insert into destinations (teacher_id, province)
select id, 'พัทลุง' from t;

-- 50) จุฑามาศ นวลนิล (ดนตรีสากล) — secondary, สงขลา
with t as (
  insert into teachers (line_user_id, display_name, position, service_type, origin_province, origin_district, teaching_group, subject, transfer_round, transfer_year, facebook_url, source, invite_code)
  values ('seed:manual:' || encode(gen_random_bytes(6), 'hex'), 'จุฑามาศ นวลนิล', 'teacher', 'secondary', 'สงขลา', 'นาทวี', 'art', 'ดนตรีสากล', null, null, null, 'facebook_import', encode(gen_random_bytes(4), 'hex'))
  returning id
)
insert into destinations (teacher_id, province)
select id, 'ยะลา' from t;

-- 51) Rapkhwan Suwannarat (นาฏศิลป์) — primary, ปัตตานี
with t as (
  insert into teachers (line_user_id, display_name, position, service_type, origin_province, origin_district, origin_zone, teaching_group, subject, transfer_round, transfer_year, facebook_url, source, invite_code)
  values ('seed:manual:' || encode(gen_random_bytes(6), 'hex'), 'Rapkhwan Suwannarat', 'teacher', 'primary', 'ปัตตานี', 'โคกโพธิ์', 'เขต 2', 'art', 'นาฏศิลป์', null, null, null, 'facebook_import', encode(gen_random_bytes(4), 'hex'))
  returning id
)
insert into destinations (teacher_id, province, zone, district)
select id, 'สงขลา', 'เขต 3', 'นาทวี, จะนะ' from t;

-- 52) Kanan Suphawadee (นาฏศิลป์) — secondary, ราชบุรี
with t as (
  insert into teachers (line_user_id, display_name, position, service_type, origin_province, teaching_group, subject, transfer_round, transfer_year, facebook_url, source, invite_code)
  values ('seed:manual:' || encode(gen_random_bytes(6), 'hex'), 'Kanan Suphawadee', 'teacher', 'secondary', 'ราชบุรี', 'art', 'นาฏศิลป์', null, null, null, 'facebook_import', encode(gen_random_bytes(4), 'hex'))
  returning id
)
insert into destinations (teacher_id, province)
select id, 'พระนครศรีอยุธยา' from t
union all
select id, 'สุพรรณบุรี' from t;

-- 53) Eng Engkan (นาฏศิลป์) — secondary, ขอนแก่น
with t as (
  insert into teachers (line_user_id, display_name, position, service_type, origin_province, teaching_group, subject, transfer_round, transfer_year, facebook_url, source, invite_code)
  values ('seed:manual:' || encode(gen_random_bytes(6), 'hex'), 'Eng Engkan', 'teacher', 'secondary', 'ขอนแก่น', 'art', 'นาฏศิลป์', null, null, null, 'facebook_import', encode(gen_random_bytes(4), 'hex'))
  returning id
)
insert into destinations (teacher_id, province, district)
select id, 'หนองคาย', 'โพนพิสัย' from t;

-- 54) TA Ta (ดนตรีศึกษา) — primary, นครสวรรค์
with t as (
  insert into teachers (line_user_id, display_name, position, service_type, origin_province, origin_zone, teaching_group, subject, transfer_round, transfer_year, facebook_url, source, invite_code)
  values ('seed:manual:' || encode(gen_random_bytes(6), 'hex'), 'TA Ta', 'teacher', 'primary', 'นครสวรรค์', 'เขต 1', 'art', 'ดนตรีศึกษา', null, null, null, 'facebook_import', encode(gen_random_bytes(4), 'hex'))
  returning id
)
insert into destinations (teacher_id, province)
select id, 'สุโขทัย' from t
union all
select id, 'ลำพูน' from t;

-- 55) B'bow Roongtip (นาฏศิลป์) — primary, พิจิตร
with t as (
  insert into teachers (line_user_id, display_name, position, service_type, origin_province, origin_zone, teaching_group, subject, transfer_round, transfer_year, facebook_url, source, invite_code)
  values ('seed:manual:' || encode(gen_random_bytes(6), 'hex'), 'B''bow Roongtip', 'teacher', 'primary', 'พิจิตร', 'เขต 1', 'art', 'นาฏศิลป์', null, null, null, 'facebook_import', encode(gen_random_bytes(4), 'hex'))
  returning id
)
insert into destinations (teacher_id, province, zone)
select id, 'อุตรดิตถ์', 'เขต 1' from t
union all
select id, 'สุโขทัย', null from t;

-- 56) MagicalCrocodile7300 (ศิลปศึกษา) — primary, นครราชสีมา
with t as (
  insert into teachers (line_user_id, display_name, position, service_type, origin_province, origin_zone, teaching_group, subject, transfer_round, transfer_year, facebook_url, source, invite_code)
  values ('seed:manual:' || encode(gen_random_bytes(6), 'hex'), 'MagicalCrocodile7300', 'teacher', 'primary', 'นครราชสีมา', 'เขต 4', 'art', 'ศิลปศึกษา', null, null, null, 'facebook_import', encode(gen_random_bytes(4), 'hex'))
  returning id
)
insert into destinations (teacher_id, province, zone)
select id, 'นครราชสีมา', 'เขต 1' from t;

-- 57) Gift Krittika (ศิลปศึกษา) — primary, สมุทรสาคร
with t as (
  insert into teachers (line_user_id, display_name, position, service_type, origin_province, teaching_group, subject, transfer_round, transfer_year, facebook_url, source, invite_code)
  values ('seed:manual:' || encode(gen_random_bytes(6), 'hex'), 'Gift Krittika', 'teacher', 'primary', 'สมุทรสาคร', 'art', 'ศิลปศึกษา', null, null, null, 'facebook_import', encode(gen_random_bytes(4), 'hex'))
  returning id
)
insert into destinations (teacher_id, province, zone)
select id, 'กระบี่', null from t
union all
select id, 'ตาก', 'เขต 1' from t;

-- 58) Jakkrit Pumlamnao (ศิลปศึกษา) — primary, สุราษฎร์ธานี
with t as (
  insert into teachers (line_user_id, display_name, position, service_type, origin_province, origin_zone, teaching_group, subject, transfer_round, transfer_year, facebook_url, source, invite_code)
  values ('seed:manual:' || encode(gen_random_bytes(6), 'hex'), 'Jakkrit Pumlamnao', 'teacher', 'primary', 'สุราษฎร์ธานี', 'เขต 1', 'art', 'ศิลปศึกษา', null, null, null, 'facebook_import', encode(gen_random_bytes(4), 'hex'))
  returning id
)
insert into destinations (teacher_id, province, zone)
select id, 'นครศรีธรรมราช', 'เขต 1, เขต 2, เขต 4' from t
union all
select id, 'สุราษฎร์ธานี', 'เขต 2, เขต 3' from t;

-- 59) ครูธมกร ครูวาตะ (ศิลปศึกษา) — primary, ขอนแก่น
with t as (
  insert into teachers (line_user_id, display_name, position, service_type, origin_province, origin_zone, teaching_group, subject, transfer_round, transfer_year, facebook_url, source, invite_code)
  values ('seed:manual:' || encode(gen_random_bytes(6), 'hex'), 'ครูธมกร ครูวาตะ', 'teacher', 'primary', 'ขอนแก่น', 'เขต 2', 'art', 'ศิลปศึกษา', null, null, null, 'facebook_import', encode(gen_random_bytes(4), 'hex'))
  returning id
)
insert into destinations (teacher_id, province)
select id, 'ร้อยเอ็ด' from t;

-- 60) Yyyyyy12 (ศิลปะ) — primary, สุราษฎร์ธานี
with t as (
  insert into teachers (line_user_id, display_name, position, service_type, origin_province, origin_zone, teaching_group, subject, transfer_round, transfer_year, facebook_url, source, invite_code)
  values ('seed:manual:' || encode(gen_random_bytes(6), 'hex'), 'Yyyyyy12', 'teacher', 'primary', 'สุราษฎร์ธานี', 'เขต 2', 'art', 'ศิลปะ', null, null, null, 'facebook_import', encode(gen_random_bytes(4), 'hex'))
  returning id
)
insert into destinations (teacher_id, province, zone)
select id, 'นครศรีธรรมราช', 'เขต 1, เขต 4' from t;

-- 61) HandsomeMouse2812 (ดนตรี) — primary, สกลนคร
with t as (
  insert into teachers (line_user_id, display_name, position, service_type, origin_province, origin_zone, teaching_group, subject, transfer_round, transfer_year, facebook_url, source, invite_code)
  values ('seed:manual:' || encode(gen_random_bytes(6), 'hex'), 'HandsomeMouse2812', 'teacher', 'primary', 'สกลนคร', 'เขต 2', 'art', 'ดนตรี', null, null, null, 'facebook_import', encode(gen_random_bytes(4), 'hex'))
  returning id
)
insert into destinations (teacher_id, province, zone)
select id, 'อุดรธานี', 'เขต 1' from t;

-- 62) PeacefulCamel5937 (ดนตรีศึกษา) — primary, ระนอง
with t as (
  insert into teachers (line_user_id, display_name, position, service_type, origin_province, teaching_group, subject, transfer_round, transfer_year, facebook_url, source, invite_code)
  values ('seed:manual:' || encode(gen_random_bytes(6), 'hex'), 'PeacefulCamel5937', 'teacher', 'primary', 'ระนอง', 'art', 'ดนตรีศึกษา', null, null, null, 'facebook_import', encode(gen_random_bytes(4), 'hex'))
  returning id
)
insert into destinations (teacher_id, province)
select id, 'ภูเก็ต' from t;

-- 63) HumbleTulip5959 (ศิลปศึกษา) — primary, นครศรีธรรมราช
with t as (
  insert into teachers (line_user_id, display_name, position, service_type, origin_province, origin_zone, teaching_group, subject, transfer_round, transfer_year, facebook_url, source, invite_code)
  values ('seed:manual:' || encode(gen_random_bytes(6), 'hex'), 'HumbleTulip5959', 'teacher', 'primary', 'นครศรีธรรมราช', 'เขต 2', 'art', 'ศิลปศึกษา', null, null, null, 'facebook_import', encode(gen_random_bytes(4), 'hex'))
  returning id
)
insert into destinations (teacher_id, province)
select id, 'สุราษฎร์ธานี' from t;

-- 64) มินตรา กินกาแฟยังวันนี้ (ศิลปศึกษา) — secondary, นครพนม
with t as (
  insert into teachers (line_user_id, display_name, position, service_type, origin_province, teaching_group, subject, transfer_round, transfer_year, facebook_url, source, invite_code)
  values ('seed:manual:' || encode(gen_random_bytes(6), 'hex'), 'มินตรา กินกาแฟยังวันนี้', 'teacher', 'secondary', 'นครพนม', 'art', 'ศิลปศึกษา', null, null, null, 'facebook_import', encode(gen_random_bytes(4), 'hex'))
  returning id
)
insert into destinations (teacher_id, province, district)
select id, 'ขอนแก่น', 'เมือง, กระนวน' from t
union all
select id, 'มหาสารคาม', 'เมือง' from t;

-- 65) Natthakan Laingam (นาฏศิลป์) — primary, ศรีสะเกษ
with t as (
  insert into teachers (line_user_id, display_name, position, service_type, origin_province, origin_zone, teaching_group, subject, transfer_round, transfer_year, facebook_url, source, invite_code)
  values ('seed:manual:' || encode(gen_random_bytes(6), 'hex'), 'Natthakan Laingam', 'teacher', 'primary', 'ศรีสะเกษ', 'เขต 1', 'art', 'นาฏศิลป์', null, 2027, null, 'facebook_import', encode(gen_random_bytes(4), 'hex'))
  returning id
)
insert into destinations (teacher_id, province, zone, district)
select id, 'อุบลราชธานี', 'เขต 5', 'เดชอุดม' from t;

-- 66) Musa Logo (อุตสาหกรรมศิลป์) — primary, ปัตตานี
with t as (
  insert into teachers (line_user_id, display_name, position, service_type, origin_province, origin_zone, teaching_group, subject, transfer_round, transfer_year, facebook_url, source, invite_code)
  values ('seed:manual:' || encode(gen_random_bytes(6), 'hex'), 'Musa Logo', 'teacher', 'primary', 'ปัตตานี', 'เขต 1', 'art', 'อุตสาหกรรมศิลป์', null, null, null, 'facebook_import', encode(gen_random_bytes(4), 'hex'))
  returning id
)
insert into destinations (teacher_id, province, zone)
select id, 'ฉะเชิงเทรา', 'เขต 1' from t;

-- 67) CopperGoldfish4349 — primary, เชียงราย
with t as (
  insert into teachers (line_user_id, display_name, position, service_type, origin_province, teaching_group, subject, transfer_round, transfer_year, facebook_url, source, invite_code)
  values ('seed:manual:' || encode(gen_random_bytes(6), 'hex'), 'CopperGoldfish4349', 'teacher', 'primary', 'เชียงราย', 'art', null, null, null, null, 'facebook_import', encode(gen_random_bytes(4), 'hex'))
  returning id
)
insert into destinations (teacher_id, province)
select id, 'เชียงราย' from t;

-- 68) VioletSquirrel9719 (ดนตรีไทย) — secondary, กรุงเทพมหานคร
with t as (
  insert into teachers (line_user_id, display_name, position, service_type, origin_province, origin_zone, teaching_group, subject, transfer_round, transfer_year, facebook_url, source, invite_code)
  values ('seed:manual:' || encode(gen_random_bytes(6), 'hex'), 'VioletSquirrel9719', 'teacher', 'secondary', 'กรุงเทพมหานคร', 'เขต 2', 'art', 'ดนตรีไทย', null, null, null, 'facebook_import', encode(gen_random_bytes(4), 'hex'))
  returning id
)
insert into destinations (teacher_id, province, zone)
select id, 'กรุงเทพมหานคร', 'เขต 1' from t;

-- 69) GentleGuava7435 (นาฏศิลป์) — primary, สระบุรี
with t as (
  insert into teachers (line_user_id, display_name, position, service_type, origin_province, origin_zone, teaching_group, subject, transfer_round, transfer_year, facebook_url, source, invite_code)
  values ('seed:manual:' || encode(gen_random_bytes(6), 'hex'), 'GentleGuava7435', 'teacher', 'primary', 'สระบุรี', 'เขต 2', 'art', 'นาฏศิลป์', '1', 2027, null, 'facebook_import', encode(gen_random_bytes(4), 'hex'))
  returning id
)
insert into destinations (teacher_id, province, zone)
select id, 'นครราชสีมา', 'เขต 1, เขต 5, เขต 4' from t;

-- 70) Kunnika Jaipeng (ศิลปศึกษา) — primary, ชัยภูมิ
with t as (
  insert into teachers (line_user_id, display_name, position, service_type, origin_province, origin_zone, teaching_group, subject, transfer_round, transfer_year, facebook_url, source, invite_code)
  values ('seed:manual:' || encode(gen_random_bytes(6), 'hex'), 'Kunnika Jaipeng', 'teacher', 'primary', 'ชัยภูมิ', 'เขต 3', 'art', 'ศิลปศึกษา', null, null, null, 'facebook_import', encode(gen_random_bytes(4), 'hex'))
  returning id
)
insert into destinations (teacher_id, province, zone)
select id, 'นครราชสีมา', 'เขต 5' from t;

-- 71) HandsomePelican1460 (ทัศนศิลป์) — primary, ยะลา
with t as (
  insert into teachers (line_user_id, display_name, position, service_type, origin_province, origin_zone, teaching_group, subject, transfer_round, transfer_year, facebook_url, source, invite_code)
  values ('seed:manual:' || encode(gen_random_bytes(6), 'hex'), 'HandsomePelican1460', 'teacher', 'primary', 'ยะลา', 'เขต 2', 'art', 'ทัศนศิลป์', null, null, null, 'facebook_import', encode(gen_random_bytes(4), 'hex'))
  returning id
)
insert into destinations (teacher_id, province, zone)
select id, 'ยะลา', 'เขต 1' from t;

-- 72) ณพัฒน์สา แก้วบวร (นาฏศิลป์) — primary, ลพบุรี
with t as (
  insert into teachers (line_user_id, display_name, position, service_type, origin_province, origin_zone, teaching_group, subject, transfer_round, transfer_year, facebook_url, source, invite_code)
  values ('seed:manual:' || encode(gen_random_bytes(6), 'hex'), 'ณพัฒน์สา แก้วบวร', 'teacher', 'primary', 'ลพบุรี', 'เขต 1', 'art', 'นาฏศิลป์', null, null, null, 'facebook_import', encode(gen_random_bytes(4), 'hex'))
  returning id
)
insert into destinations (teacher_id, province)
select id, 'อ่างทอง' from t;

-- 73) BK Benjarat Keankong (นาฏศิลป์) — primary, นครราชสีมา
with t as (
  insert into teachers (line_user_id, display_name, position, service_type, origin_province, origin_zone, teaching_group, subject, transfer_round, transfer_year, facebook_url, source, invite_code)
  values ('seed:manual:' || encode(gen_random_bytes(6), 'hex'), 'BK Benjarat Keankong', 'teacher', 'primary', 'นครราชสีมา', 'เขต 2', 'art', 'นาฏศิลป์', null, null, null, 'facebook_import', encode(gen_random_bytes(4), 'hex'))
  returning id
)
insert into destinations (teacher_id, province, zone)
select id, 'ยโสธร', 'เขต 1' from t;

-- 74) GratefulPersimmon3808 (นาฏศิลป์) — primary, ปทุมธานี
with t as (
  insert into teachers (line_user_id, display_name, position, service_type, origin_province, origin_zone, teaching_group, subject, transfer_round, transfer_year, facebook_url, source, invite_code)
  values ('seed:manual:' || encode(gen_random_bytes(6), 'hex'), 'GratefulPersimmon3808', 'teacher', 'primary', 'ปทุมธานี', 'เขต 1', 'art', 'นาฏศิลป์', '1', 2027, null, 'facebook_import', encode(gen_random_bytes(4), 'hex'))
  returning id
)
insert into destinations (teacher_id, province)
select id, 'ราชบุรี' from t
union all
select id, 'เพชรบุรี' from t;

-- 75) Xian (นาฏศิลป์) — primary, ระยอง
with t as (
  insert into teachers (line_user_id, display_name, position, service_type, origin_province, origin_zone, teaching_group, subject, transfer_round, transfer_year, facebook_url, source, invite_code)
  values ('seed:manual:' || encode(gen_random_bytes(6), 'hex'), 'Xian', 'teacher', 'primary', 'ระยอง', 'เขต 1', 'art', 'นาฏศิลป์', null, null, null, 'facebook_import', encode(gen_random_bytes(4), 'hex'))
  returning id
)
insert into destinations (teacher_id, province)
select id, 'นนทบุรี' from t
union all
select id, 'กรุงเทพมหานคร' from t;
